/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_socket_ClientActivity */

#ifndef _Included_com_ziv_socket_ClientActivity
#define _Included_com_ziv_socket_ClientActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_socket_ClientActivity
 * Method:    nativeStartTcpClient
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ziv_socket_ClientActivity_nativeStartTcpClient
  (JNIEnv *, jobject, jstring, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
