/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_socket_LocalActivity */

#ifndef _Included_com_ziv_socket_LocalActivity
#define _Included_com_ziv_socket_LocalActivity
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_ziv_socket_LocalActivity
 * Method:    nativeStartLocalServer
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ziv_socket_LocalActivity_nativeStartLocalServer
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
