/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziv_socket_ServerActivity */

#ifndef _Included_com_ziv_socket_ServerActivity
#define _Included_com_ziv_socket_ServerActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziv_socket_ServerActivity
 * Method:    nativeStartTcpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ziv_socket_ServerActivity_nativeStartTcpServer
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_ziv_socket_ServerActivity
 * Method:    nativeStartUdpServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_ziv_socket_ServerActivity_nativeStartUdpServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
